import javax.swing.*;
import java.sql.*;

public class bill extends javax.swing.JFrame {
    public int total_cost;

    /** Creates new form bill */
    public bill() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BILL.png"))); // NOI18N

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CUSTOMER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 120, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CAR NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DATE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 100, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("TOTAL COST ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 270, 100, 30);

        l5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(180, 270, 220, 30);

        jButton1.setText("GENERATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 320, 130, 30);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 320, 80, 30);

        jButton3.setText("CONFIRM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 320, 90, 30);

        l6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(l6);
        l6.setBounds(190, 210, 220, 30);

        l7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(l7);
        l7.setBounds(190, 150, 220, 30);

        l8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(l8);
        l8.setBounds(190, 90, 220, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BILL.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-6, -6, 620, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

l8.setText(""+ booking1.name);
l7.setText(""+ cars.carname);
l6.setText(""+booking1.Ddate);
int n=booking1.n;
int c=cars.carno;
    if(c==1){
        total_cost = n*2000;
        l5.setText(""+total_cost);
    }
else if(c==2){
        total_cost = n*2500;
        l5.setText(""+total_cost);
}
else if(c==3){
        total_cost = n*2500;
        l5.setText(""+total_cost);
}
else if(c==4){
    total_cost = n*3000;
    l5.setText(""+total_cost);
}
else if(c==5){
    total_cost = n*3500;
    l5.setText(""+total_cost);
}
else if(c==6){
    total_cost = n*4000;    
    l5.setText(""+total_cost);
}
else if(c==7){
        total_cost = n*5000;
        l5.setText(""+total_cost);
}
else if(c==8){
        total_cost = n*6000;
        l5.setText(""+n*total_cost);
}
else if(c==9){
        total_cost = n*6000;
        l5.setText(""+total_cost);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
    {
Class.forName("com.mysql.jdbc.Driver");
         Connection con=(Connection)DriverManager.getConnection
                 ("jdbc:mysql://localhost:3306/car_rental","root" , "deva321");
         Statement stmt = (Statement)con.createStatement();
         String query="INSERT INTO bills VALUES ( '"+booking1.name+"',  '"+cars.carname+"', '"+total_cost+"', '"+booking1.Ddate+"' );";
stmt.executeUpdate(query);
        }
catch(Exception e)
             {
JOptionPane.showMessageDialog(this, e.getMessage());
             }
JOptionPane.showMessageDialog(this,"booking confirmed");
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    // End of variables declaration//GEN-END:variables

}
