import javax.swing.ImageIcon;



public class cars extends javax.swing.JFrame {

    /** Creates new form cars */
    public cars() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        t = new javax.swing.JLabel();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        buttonGroup1.add(r3);
        r3.setText("Honda City");
        r3.setOpaque(false);
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3);
        r3.setBounds(50, 120, 110, 23);

        buttonGroup1.add(r4);
        r4.setText("Ciaz");
        r4.setOpaque(false);
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        getContentPane().add(r4);
        r4.setBounds(50, 140, 110, 30);

        buttonGroup1.add(r5);
        r5.setText("Ford Eco Sport");
        r5.setOpaque(false);
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });
        getContentPane().add(r5);
        r5.setBounds(50, 170, 110, 23);

        buttonGroup1.add(r6);
        r6.setText("Mahindra Scorpio");
        r6.setOpaque(false);
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        getContentPane().add(r6);
        r6.setBounds(50, 190, 110, 30);

        r1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(r1);
        r1.setText("Ford Figo");
        r1.setOpaque(false);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(50, 70, 110, 23);

        r2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(r2);
        r2.setText("Honda Amaze");
        r2.setOpaque(false);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(50, 90, 110, 30);

        buttonGroup1.add(r7);
        r7.setText("XUV 500");
        r7.setOpaque(false);
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });
        getContentPane().add(r7);
        r7.setBounds(50, 220, 110, 23);
        getContentPane().add(t);
        t.setBounds(280, 80, 380, 210);

        buttonGroup1.add(r8);
        r8.setText("Mercedes A-class");
        r8.setActionCommand("[0,0,0]");
        r8.setOpaque(false);
        r8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8ActionPerformed(evt);
            }
        });
        getContentPane().add(r8);
        r8.setBounds(50, 250, 110, 23);

        buttonGroup1.add(r9);
        r9.setText("BMW 3-Series");
        r9.setOpaque(false);
        r9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9ActionPerformed(evt);
            }
        });
        getContentPane().add(r9);
        r9.setBounds(50, 270, 110, 23);

        jButton1.setText("Proceed To Billing ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 310, 180, 30);

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 310, 130, 30);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 310, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/choose.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 690, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int carno;
public static String carname;
    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
if(r5.isSelected())
        t.setIcon(new ImageIcon("images/Ford-Ecosport.JPG"));
carno=5;
carname="ecosport";
// TODO add your handling code here:
    }//GEN-LAST:event_r5ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
    if(r1.isSelected())
                    t.setIcon(new ImageIcon("images/Ford-Figo.JPG"));
    carno=1;
    carname="ford figo";
    // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
     if(r2.isSelected())
        t.setIcon(new ImageIcon("images/Honda-Amaze.JPG"));
     carno=2;
carname="honda amaxe";// TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
if(r3.isSelected())
        t.setIcon(new ImageIcon("images/Honda_city.JPG"));
carno=3;
carname="honda city";// TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
if(r4.isSelected())
        t.setIcon(new ImageIcon("images/Suzuki-Ciaz.JPG"));
carno=4;
carname="suzuki ciaz";// TODO add your handling code here:
    }//GEN-LAST:event_r4ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
if(r6.isSelected())
        t.setIcon(new ImageIcon("images/SCorpio.JPG"));
carno=6;
carname="mahindra scorpio";// TODO add your handling code here:
    }//GEN-LAST:event_r6ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
if(r7.isSelected())
        t.setIcon(new ImageIcon("images/XUV.JPG"));
carno=7;
carname="XUV 500";// TODO add your handling code here:
    }//GEN-LAST:event_r7ActionPerformed

    private void r8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8ActionPerformed
if(r8.isSelected())
        t.setIcon(new ImageIcon("images/Merc-A-Class.JPG"));
carno=8;
carname="mercedes benz A-Class";// TODO add your handling code here:
    }//GEN-LAST:event_r8ActionPerformed

    private void r9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9ActionPerformed
if(r9.isSelected())
        t.setIcon(new ImageIcon("images/BMW-3seires.JPG"));
carno=9;
carname="BMW 3 Series";// TODO add your handling code here:
    }//GEN-LAST:event_r9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
new booking1().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
new login1().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables

}
